### ISSUE TITLE
Misnamed file

### ISSUE THREAD

**Issue by De-Clan-C** [sovsay11/INFO-1200-X02-Fall-2022#1]
The dot at the end of the name of the file "AshrafAbudu.py." is causing git to not be able to pull the repo onto my computer. If you could kindly change that, it would be great! Thanks.
Picture of the error: ![image](https://user-images.githubusercontent.com/108594239/188039808-3ffac750-0a96-4bce-b78a-9fa03daf66d9.png)

**Comment by sovsay11** [comment]
Just deleted the file. Thanks for catching this.
